### ISSUE TITLE
Collision Resistant IDs

### ISSUE THREAD

**Issue by smhmayboudi** [ethanniser/beth-b2b-saas#9]
Thanks in advanced for your contribution. I study this project and I would like to know is there any specific reason you choose the `https://www.npmjs.com/package/@paralleldrive/cuid2` ? there are other option which I would like to know your idea. `https://www.npmjs.com/package/scuid` and `https://www.npmjs.com/package/@bugsnag/cuid`. https://npmtrends.com/@bugsnag/cuid-vs-@paralleldrive/cuid2-vs-scuid

**Comment by ethanniser** [comment]
there is no specific reason I choose that library
there are lots of great id generating libraries available, feel free to choose the one you think fits best in your project
